import type { Metadata } from "next";
import {Providers} from "./providers";
import "./globals.css";
import NavigatorComp from "~/components/navigator/navigator";
import React from "react";
import customTheme from "~/app/theme";
import {ChakraProvider} from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
